services:
  - type: web
    name: finance-tracker-api
    env: node
    buildCommand: cd server && npm install && npx prisma generate && npm run build
    startCommand: cd server && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString

databases:
  - name: finance-tracker-db
    databaseName: finance_tracker
    user: finance_tracker_user 